name: CI to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag
        run: |
          docker build -t saginsin/survefy:latest .
          docker tag bf17484fccaba9fc01e1ad1ddb452732c4307b6376c35f59d3adf59f44e4664a saginsin/survefy:latest

      - name: Push to DockerHub
        run: docker push saginsin/survefy:latest

